### ISSUE TITLE
Problem when using crontab

### ISSUE THREAD

**Issue by dmrlawson** [stblackbird/nasa-apod-background#3]
The recent pull request reminded me of something I had meant to ask you about.

I'm using Ubuntu 14.04 (although I think it affected earlier versions too) and if I set the script to run directly via crontab, it doesn't work. It seems it needs a reference to the current session (a little beyond my understanding) and I found the following fix:

PID=$(pgrep gnome-session)
export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$PID/environ|cut -d= -f2-)

By using crontab to run a wrapper script which executes those two lines before the python script, everything works fine.

I just wondered whether this should be put in the readme or something? Maybe there's a better solution that could be put in the python script?

**Comment by stblackbird** [comment]
Sorry I didn't merge your code earlier, was trully busy those last months and forgot about the thing :)
Anyway, better late than never!
